FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    gcc \
    libc6-compat

COPY frontend/package*.json ./
RUN npm config set registry https://mirror2.chabokan.net/npm/

COPY frontend/ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]