FROM node:20-alpine

WORKDIR /app

COPY backend/package*.json ./
RUN npm config set registry https://mirror2.chabokan.net/npm/ && npm install

COPY backend/ ./

EXPOSE 5000

CMD ["npm", "run", "dev"]
