FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY backend/package*.json ./
RUN npm config set registry https://mirror2.chabokan.net/npm/

# Copy source
COPY backend/ ./

EXPOSE 5000

# Use ts-node-dev for hot reload
CMD ["npm", "run", "dev"]