import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1780479245602 implements MigrationInterface {
    name = 'InitialSchema1780479245602'

    public async up(queryRunner: QueryRunner): Promise<void> {
<<<<<<< HEAD
        await queryRunner.query(`DROP INDEX "public"."idx_notes_title_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notes_content_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_links_title_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_links_url_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_links_description_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_snippets_title_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_snippets_content_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_snippets_description_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prompts_title_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prompts_content_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prompts_description_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_infras_title_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_infras_content_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_infras_description_trgm"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE INDEX "idx_infras_description_trgm" ON "infrastructures" ("description") `);
        await queryRunner.query(`CREATE INDEX "idx_infras_content_trgm" ON "infrastructures" ("content") `);
        await queryRunner.query(`CREATE INDEX "idx_infras_title_trgm" ON "infrastructures" ("title") `);
        await queryRunner.query(`CREATE INDEX "idx_prompts_description_trgm" ON "prompts" ("description") `);
        await queryRunner.query(`CREATE INDEX "idx_prompts_content_trgm" ON "prompts" ("content") `);
        await queryRunner.query(`CREATE INDEX "idx_prompts_title_trgm" ON "prompts" ("title") `);
        await queryRunner.query(`CREATE INDEX "idx_snippets_description_trgm" ON "snippets" ("description") `);
        await queryRunner.query(`CREATE INDEX "idx_snippets_content_trgm" ON "snippets" ("content") `);
        await queryRunner.query(`CREATE INDEX "idx_snippets_title_trgm" ON "snippets" ("title") `);
        await queryRunner.query(`CREATE INDEX "idx_links_description_trgm" ON "links" ("description") `);
        await queryRunner.query(`CREATE INDEX "idx_links_url_trgm" ON "links" ("url") `);
        await queryRunner.query(`CREATE INDEX "idx_links_title_trgm" ON "links" ("title") `);
        await queryRunner.query(`CREATE INDEX "idx_notes_content_trgm" ON "notes" ("content") `);
        await queryRunner.query(`CREATE INDEX "idx_notes_title_trgm" ON "notes" ("title") `);
=======
        await queryRunner.query(`CREATE TABLE "user_vaults" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer NOT NULL, "encrypted_vault_key" text, "is_enabled" boolean NOT NULL DEFAULT false, "enabled_at" TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e16cf2e24234539ac21a8aa47c1" UNIQUE ("user_id"), CONSTRAINT "PK_d8cc1d4dc2c0a791f1f04cfa398" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notes" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "content" text, "is_pinned" boolean NOT NULL DEFAULT false, "category_id" integer, "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_af6206538ea96c4e77e9f400c3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_216d98067d764c901b77d281e1" ON "notes" ("is_pinned") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d5c6951d7233408f4f9359a5c" ON "notes" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7708dcb62ff332f0eaf9f0743a" ON "notes" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_711a0447a29a696b7989f23c1c" ON "notes" ("user_id", "updated_at") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "parent_id" integer, "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_88cea2dc9c31951d06437879b4" ON "categories" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2296b7fe012d95646fa41921c8" ON "categories" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "links" ("id" SERIAL NOT NULL, "url" character varying(2048) NOT NULL, "title" character varying(255) NOT NULL, "description" text, "username" character varying(100), "password_encrypted" character varying(255), "email" character varying(255), "phone" character varying(20), "is_favorite" boolean NOT NULL DEFAULT false, "category_id" integer, "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ecf17f4a741d3c5ba0b4c5ab4b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81581f4e2837c2cb26c19c88a4" ON "links" ("is_favorite") `);
        await queryRunner.query(`CREATE INDEX "IDX_42692729856abf63f8081f2939" ON "links" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f8dea86e48a7216c4f5369c1e" ON "links" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1368f71f1b166fe3ef1d8782c3" ON "links" ("user_id", "updated_at") `);
        await queryRunner.query(`CREATE TABLE "tags" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_74603743868d1e4f4fc2c0225b" ON "tags" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "username" character varying(50), "email" character varying(255), "password_hash" character varying(255) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "taggables" ("id" SERIAL NOT NULL, "tag_id" integer NOT NULL, "taggable_id" integer NOT NULL, "taggable_type" character varying(20) NOT NULL, CONSTRAINT "PK_c5a93f59be62be00668b8dcaa50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b28c87e447a9dbad197bca5d26" ON "taggables" ("tag_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a06ae520a10d05be396bb86669" ON "taggables" ("taggable_id", "taggable_type") `);
        await queryRunner.query(`CREATE TABLE "snippets" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "content" text NOT NULL, "language" character varying(50) NOT NULL DEFAULT 'txt', "snippet_type" character varying(50) NOT NULL DEFAULT 'code', "description" text, "metadata" text, "is_favorite" boolean NOT NULL DEFAULT false, "category_id" integer, "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_da592ff802b6af1369e622402a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_17543d15b65b97e3045127b730" ON "snippets" ("language") `);
        await queryRunner.query(`CREATE INDEX "IDX_1155593dacb83f773f78d04781" ON "snippets" ("snippet_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1b13ec8799b1d5969cc865db4" ON "snippets" ("is_favorite") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a7cf5643dd02e059da059bd4d" ON "snippets" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_95bdf4824ed1cb9a195e4af88e" ON "snippets" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2337649f9df8edfdebf4f4d98c" ON "snippets" ("user_id", "updated_at") `);
        await queryRunner.query(`CREATE TABLE "secure_fields" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer NOT NULL, "module" character varying NOT NULL, "record_id" character varying NOT NULL, "field_name" character varying NOT NULL, "encrypted_value" text NOT NULL, "iv" text NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6cf3cea2c8bdf8a1bea99ba96da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c586e1b057a00eb423f3d5c650" ON "secure_fields" ("user_id", "module", "record_id", "field_name") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" SERIAL NOT NULL, "tokenHash" character varying(64) NOT NULL, "user_id" integer NOT NULL, "expires_at" TIMESTAMP NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c25bc63d248ca90e8dcc1d92d06" UNIQUE ("tokenHash"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "prompt_collections" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" text, "color" character varying(20), "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_024899935e4c3cdfdc35e39e909" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70f5a09e0b436c75bb9b861c20" ON "prompt_collections" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_264404d916c41fd1727c81b3ab" ON "prompt_collections" ("user_id", "updated_at") `);
        await queryRunner.query(`CREATE TABLE "prompt_collection_items" ("id" SERIAL NOT NULL, "collection_id" integer NOT NULL, "prompt_id" integer NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "added_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fdd1e827dbf2dc69a41cf4317eb" UNIQUE ("collection_id", "prompt_id"), CONSTRAINT "PK_dffe35a5222007711e071b8f046" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b1377326ad69d2d1e8e9e319d8" ON "prompt_collection_items" ("collection_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0404fe76604005010d0a4eff03" ON "prompt_collection_items" ("collection_id", "sort_order") `);
        await queryRunner.query(`CREATE TABLE "prompts" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "content" text NOT NULL, "description" text, "prompt_type" character varying(50) NOT NULL, "target_ai" character varying(50), "expected_output" text, "usage_count" integer NOT NULL DEFAULT '0', "last_used_at" TIMESTAMP, "is_favorite" boolean NOT NULL DEFAULT false, "variables" jsonb DEFAULT '[]'::jsonb, "versions" jsonb DEFAULT '[]'::jsonb, "category_id" integer, "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_21f33798862975179e40b216a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f462df9c2cd7ad2e6835734456" ON "prompts" ("prompt_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_04f942302c0d57cc2aeba51069" ON "prompts" ("target_ai") `);
        await queryRunner.query(`CREATE INDEX "IDX_089611188df6acf76811ca4f4a" ON "prompts" ("is_favorite") `);
        await queryRunner.query(`CREATE INDEX "IDX_025ceda56c30f5c7edaeee2120" ON "prompts" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa88f45bd24d019088a898cf66" ON "prompts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_338f38bb749ffd1e57268c77d1" ON "prompts" ("user_id", "updated_at") `);
        await queryRunner.query(`CREATE TABLE "projects" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" text, "color" character varying(20), "emoji" character varying(10), "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bd55b203eb9f92b0c839038001" ON "projects" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_10955c08226561ea39d4169967" ON "projects" ("user_id", "updated_at") `);
        await queryRunner.query(`CREATE TABLE "project_items" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "item_type" character varying(30) NOT NULL, "item_id" integer NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "added_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_63e788c2281d2e43ee0803bfae5" UNIQUE ("project_id", "item_type", "item_id"), CONSTRAINT "PK_07d1a90c615b34f0773824a505e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e699a79a08443cab8ea543108" ON "project_items" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb5d4068d5de22bac3b939e00e" ON "project_items" ("item_type", "item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b2917b97d8646dbfefcce0d6c2" ON "project_items" ("project_id", "sort_order") `);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" SERIAL NOT NULL, "token" character varying(64) NOT NULL, "user_id" integer NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab673f0e63eac966762155508ee" UNIQUE ("token"), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "infrastructures" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "infra_type" character varying(50) NOT NULL, "description" text, "content" text NOT NULL, "metadata" text, "is_favorite" boolean NOT NULL DEFAULT false, "category_id" integer, "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_721c61577363b533ca9f73c75db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_21aa5b2c72c5898563b74df9a2" ON "infrastructures" ("infra_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_24b3f13daee9bc42ff141228ad" ON "infrastructures" ("is_favorite") `);
        await queryRunner.query(`CREATE INDEX "IDX_056276ceab3e2b2fac90997f80" ON "infrastructures" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_09fef2427c4b91bc28c2207f0e" ON "infrastructures" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c4d36956b407b2e626f57da09e" ON "infrastructures" ("user_id", "updated_at") `);
        await queryRunner.query(`CREATE TABLE "api_collections" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text, "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b73f8356cfdcc3b5ccc9f0fdac6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "api_endpoints" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "url" character varying(2048) NOT NULL, "method" character varying(10) NOT NULL, "description" text, "headers" text, "query_params" text, "body" text, "body_type" character varying(50), "auth_type" character varying(20) NOT NULL DEFAULT 'none', "auth_data" text, "example_response" text, "is_favorite" boolean NOT NULL DEFAULT false, "collection_id" integer, "category_id" integer, "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86582e0b469aab3e946ed53be2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "api_environments" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "variables" text, "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f32ae0fefcdda8cdf5281693bf5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "notes" ADD CONSTRAINT "FK_3d5c6951d7233408f4f9359a5c1" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notes" ADD CONSTRAINT "FK_7708dcb62ff332f0eaf9f0743a7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_2296b7fe012d95646fa41921c8b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "links" ADD CONSTRAINT "FK_42692729856abf63f8081f29394" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "links" ADD CONSTRAINT "FK_9f8dea86e48a7216c4f5369c1e4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_74603743868d1e4f4fc2c0225b6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taggables" ADD CONSTRAINT "FK_b28c87e447a9dbad197bca5d264" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "snippets" ADD CONSTRAINT "FK_8a7cf5643dd02e059da059bd4de" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "snippets" ADD CONSTRAINT "FK_95bdf4824ed1cb9a195e4af88ed" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prompt_collections" ADD CONSTRAINT "FK_70f5a09e0b436c75bb9b861c203" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prompt_collection_items" ADD CONSTRAINT "FK_b1377326ad69d2d1e8e9e319d8a" FOREIGN KEY ("collection_id") REFERENCES "prompt_collections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prompts" ADD CONSTRAINT "FK_025ceda56c30f5c7edaeee2120c" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prompts" ADD CONSTRAINT "FK_aa88f45bd24d019088a898cf66b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_bd55b203eb9f92b0c8390380010" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_items" ADD CONSTRAINT "FK_7e699a79a08443cab8ea543108f" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "infrastructures" ADD CONSTRAINT "FK_056276ceab3e2b2fac90997f807" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "infrastructures" ADD CONSTRAINT "FK_09fef2427c4b91bc28c2207f0e2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_collections" ADD CONSTRAINT "FK_fb96ff532cb61068de5ad8cc329" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_endpoints" ADD CONSTRAINT "FK_f99233f809a17702f984c6151f1" FOREIGN KEY ("collection_id") REFERENCES "api_collections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_endpoints" ADD CONSTRAINT "FK_d71b00b389e5a1472398596a64c" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_endpoints" ADD CONSTRAINT "FK_84031f8ba4b1aead3c5f51dd0f1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_environments" ADD CONSTRAINT "FK_3b91122ef0a12cf27e8ceaff008" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "api_environments" DROP CONSTRAINT "FK_3b91122ef0a12cf27e8ceaff008"`);
        await queryRunner.query(`ALTER TABLE "api_endpoints" DROP CONSTRAINT "FK_84031f8ba4b1aead3c5f51dd0f1"`);
        await queryRunner.query(`ALTER TABLE "api_endpoints" DROP CONSTRAINT "FK_d71b00b389e5a1472398596a64c"`);
        await queryRunner.query(`ALTER TABLE "api_endpoints" DROP CONSTRAINT "FK_f99233f809a17702f984c6151f1"`);
        await queryRunner.query(`ALTER TABLE "api_collections" DROP CONSTRAINT "FK_fb96ff532cb61068de5ad8cc329"`);
        await queryRunner.query(`ALTER TABLE "infrastructures" DROP CONSTRAINT "FK_09fef2427c4b91bc28c2207f0e2"`);
        await queryRunner.query(`ALTER TABLE "infrastructures" DROP CONSTRAINT "FK_056276ceab3e2b2fac90997f807"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c"`);
        await queryRunner.query(`ALTER TABLE "project_items" DROP CONSTRAINT "FK_7e699a79a08443cab8ea543108f"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_bd55b203eb9f92b0c8390380010"`);
        await queryRunner.query(`ALTER TABLE "prompts" DROP CONSTRAINT "FK_aa88f45bd24d019088a898cf66b"`);
        await queryRunner.query(`ALTER TABLE "prompts" DROP CONSTRAINT "FK_025ceda56c30f5c7edaeee2120c"`);
        await queryRunner.query(`ALTER TABLE "prompt_collection_items" DROP CONSTRAINT "FK_b1377326ad69d2d1e8e9e319d8a"`);
        await queryRunner.query(`ALTER TABLE "prompt_collections" DROP CONSTRAINT "FK_70f5a09e0b436c75bb9b861c203"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "snippets" DROP CONSTRAINT "FK_95bdf4824ed1cb9a195e4af88ed"`);
        await queryRunner.query(`ALTER TABLE "snippets" DROP CONSTRAINT "FK_8a7cf5643dd02e059da059bd4de"`);
        await queryRunner.query(`ALTER TABLE "taggables" DROP CONSTRAINT "FK_b28c87e447a9dbad197bca5d264"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_74603743868d1e4f4fc2c0225b6"`);
        await queryRunner.query(`ALTER TABLE "links" DROP CONSTRAINT "FK_9f8dea86e48a7216c4f5369c1e4"`);
        await queryRunner.query(`ALTER TABLE "links" DROP CONSTRAINT "FK_42692729856abf63f8081f29394"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_2296b7fe012d95646fa41921c8b"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "notes" DROP CONSTRAINT "FK_7708dcb62ff332f0eaf9f0743a7"`);
        await queryRunner.query(`ALTER TABLE "notes" DROP CONSTRAINT "FK_3d5c6951d7233408f4f9359a5c1"`);
        await queryRunner.query(`DROP TABLE "api_environments"`);
        await queryRunner.query(`DROP TABLE "api_endpoints"`);
        await queryRunner.query(`DROP TABLE "api_collections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4d36956b407b2e626f57da09e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09fef2427c4b91bc28c2207f0e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_056276ceab3e2b2fac90997f80"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24b3f13daee9bc42ff141228ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21aa5b2c72c5898563b74df9a2"`);
        await queryRunner.query(`DROP TABLE "infrastructures"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2917b97d8646dbfefcce0d6c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb5d4068d5de22bac3b939e00e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e699a79a08443cab8ea543108"`);
        await queryRunner.query(`DROP TABLE "project_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10955c08226561ea39d4169967"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd55b203eb9f92b0c839038001"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_338f38bb749ffd1e57268c77d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa88f45bd24d019088a898cf66"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_025ceda56c30f5c7edaeee2120"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_089611188df6acf76811ca4f4a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04f942302c0d57cc2aeba51069"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f462df9c2cd7ad2e6835734456"`);
        await queryRunner.query(`DROP TABLE "prompts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0404fe76604005010d0a4eff03"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1377326ad69d2d1e8e9e319d8"`);
        await queryRunner.query(`DROP TABLE "prompt_collection_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_264404d916c41fd1727c81b3ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70f5a09e0b436c75bb9b861c20"`);
        await queryRunner.query(`DROP TABLE "prompt_collections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c586e1b057a00eb423f3d5c650"`);
        await queryRunner.query(`DROP TABLE "secure_fields"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2337649f9df8edfdebf4f4d98c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95bdf4824ed1cb9a195e4af88e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a7cf5643dd02e059da059bd4d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1b13ec8799b1d5969cc865db4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1155593dacb83f773f78d04781"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17543d15b65b97e3045127b730"`);
        await queryRunner.query(`DROP TABLE "snippets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a06ae520a10d05be396bb86669"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b28c87e447a9dbad197bca5d26"`);
        await queryRunner.query(`DROP TABLE "taggables"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74603743868d1e4f4fc2c0225b"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1368f71f1b166fe3ef1d8782c3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f8dea86e48a7216c4f5369c1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42692729856abf63f8081f2939"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81581f4e2837c2cb26c19c88a4"`);
        await queryRunner.query(`DROP TABLE "links"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2296b7fe012d95646fa41921c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88cea2dc9c31951d06437879b4"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_711a0447a29a696b7989f23c1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7708dcb62ff332f0eaf9f0743a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d5c6951d7233408f4f9359a5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_216d98067d764c901b77d281e1"`);
        await queryRunner.query(`DROP TABLE "notes"`);
        await queryRunner.query(`DROP TABLE "user_vaults"`);
>>>>>>> 0716009 (init)
    }

}
